CREATE TABLE IF NOT EXISTS inventories (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  department_id INT NOT NULL,
  incharge_id INT NOT NULL,
  description TEXT,
  location VARCHAR(100) DEFAULT '',
  status ENUM('active', 'inactive') DEFAULT 'active',
  created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS inventory_items (
  id INT PRIMARY KEY AUTO_INCREMENT,
  itemName VARCHAR(255) NOT NULL,
  itemCode VARCHAR(255) DEFAULT '',
  serialNo VARCHAR(255) DEFAULT '',
  serialNo2 VARCHAR(255) DEFAULT '',
  model VARCHAR(255) DEFAULT '',
  QRCode VARCHAR(255) DEFAULT '',
  QRCode2 VARCHAR(255) DEFAULT '',
  pageno VARCHAR(100) DEFAULT '',
  itemImage VARCHAR(255) DEFAULT '',
  value DECIMAL(12, 2) NULL,
  purchaseDate DATE NULL,
  ginNo VARCHAR(255) DEFAULT '',
  ginfile VARCHAR(255) DEFAULT '',
  poNo VARCHAR(255) DEFAULT '',
  supplier VARCHAR(255) DEFAULT '',
  funding VARCHAR(255) DEFAULT '',
  receivedfrom VARCHAR(255) DEFAULT '',
  warranty VARCHAR(255) DEFAULT '',
  location VARCHAR(255) DEFAULT '',
  remarks TEXT,
  qrcodeUrl TEXT,
  qrcode2Url TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);